-- Initial schema for the Postgres-backed `postgres` profile. Column names follow Spring Boot's
-- default snake_case physical naming strategy, so they match the JPA @Entity mappings without any
-- explicit @Column(name = ...) annotations.

-- Record of every MsgId we have already answered. The unique constraint on message_id is the real
-- idempotency guard: under concurrent duplicate delivery one INSERT wins and the other rolls back,
-- so a redelivered pacs.008 can never post to the ledger twice.
CREATE TABLE processed_message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id   VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL,   -- ACSC / PART / RJCT group status of the original run
    reason_code  VARCHAR(255),            -- ISO reason code for a RJCT; null otherwise
    pacs002xml   TEXT         NOT NULL,   -- the exact response returned the first time (replayed)
                                          -- (column is pacs002xml, not pacs002_xml: Spring's
                                          -- snake_case strategy inserts no underscore before the
                                          -- digit-adjacent "Xml" segment of the pacs002Xml field)
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_processed_msgid UNIQUE (message_id)
);

-- Double-entry ledger. Every settled transfer writes exactly two rows that net to zero: a DEBIT
-- against the debtor account and a CREDIT to the creditor.
CREATE TABLE ledger_entry (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(255)  NOT NULL,
    account_id     VARCHAR(255)  NOT NULL,
    direction      VARCHAR(255)  NOT NULL,   -- DEBIT / CREDIT (enum stored as string)
    amount         NUMERIC(19,4) NOT NULL,
    currency       VARCHAR(3)    NOT NULL,
    posted_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Postings for a transaction are read back together to assert the zero-sum invariant.
CREATE INDEX idx_ledger_txid ON ledger_entry (transaction_id);
